version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/vehicle_tracking_db
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
